### ISSUE TITLE
Input-41: Cannot read properties of null (reading 'visibleRange')

### ISSUE THREAD

**Issue by Depliix** [origin-space/originui#41]
If I want to use Input-41 (Date Picker) and then click on the date popover button, I get the following error:

```
index.js:278019 Uncaught TypeError: Cannot read properties of null (reading 'visibleRange')
    at $3f539f26b167ddde$var$CalendarGrid (index.js:278019:27)
    at renderWithHooks (index.js:306038:18)
    at updateForwardRef (index.js:308954:20)
    at beginWork (index.js:311364:16)
    at beginWork$1 (index.js:317154:14)
    at performUnitOfWork (index.js:316288:12)
    at workLoopSync (index.js:316194:5)
    at renderRootSync (index.js:316162:7)
    at recoverFromConcurrentError (index.js:315578:20)
    at performSyncWorkOnRoot (index.js:315824:20)
```

**Comment by pasqualevitiello** [comment]
Hi @Depliix, I've tried to reproduce the issue but wasn't successful. I implemented the component following the setup shown in the [React Aria documentation](https://react-spectrum.adobe.com/react-aria/DatePicker.html). If you could create a minimal reproduction repository, I'd be happy to have a look

**Comment by pasqualevitiello** [comment]
Closed for inactivity
